#!/usr/bin/env python3
"""Focused safety tests for the cross-platform card-toolchain build driver."""

from __future__ import annotations

import importlib.util
import inspect
import json
import os
from pathlib import Path
import re
import stat
import subprocess
import sys
import tempfile
import unittest
from unittest import mock


REPO_ROOT = Path(__file__).resolve().parents[2]
DRIVER_PATH = REPO_ROOT / "mainline" / "scripts" / "r46h_card_toolchain.py"
SPEC = importlib.util.spec_from_file_location("r46h_card_toolchain", DRIVER_PATH)
assert SPEC is not None and SPEC.loader is not None
DRIVER = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = DRIVER
SPEC.loader.exec_module(DRIVER)


class CardToolchainBuildDriverTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        scratch_override = os.environ.get("R46H_CARD_TEST_SCRATCH_ROOT")
        cls.scratch_root = (
            Path(scratch_override)
            if scratch_override
            else REPO_ROOT
            / "mainline"
            / "out"
            / ".cache"
            / "r46h-card-toolchain-driver-tests"
        )
        cls.scratch_root.mkdir(parents=True, exist_ok=True)

    @classmethod
    def tearDownClass(cls) -> None:
        try:
            cls.scratch_root.rmdir()
        except OSError:
            pass

    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory(dir=self.scratch_root)
        self.addCleanup(self.temporary.cleanup)
        self.fake_repo = Path(self.temporary.name) / "repo"
        (self.fake_repo / "mainline" / "tools" / "r46h-card-toolchain").mkdir(
            parents=True
        )
        (self.fake_repo / "mainline" / "out").mkdir(parents=True)

    def layout(self) -> object:
        return DRIVER.make_layout(
            str(self.fake_repo / "mainline" / "out" / ".cache" / "r46h-card-toolchain"),
            repo_root_override=self.fake_repo,
        )

    def directory_symlink_or_skip(self, link: Path, target: Path) -> None:
        try:
            link.symlink_to(target, target_is_directory=True)
        except (NotImplementedError, OSError) as error:
            self.skipTest(f"directory symlink fixture is unavailable: {error}")

    def initialize_source_repository(self) -> object:
        """Create a minimal, committed source closure for snapshot tests."""

        for source_name in DRIVER.BUILD_SOURCE_PATHS:
            source_path = self.fake_repo / source_name
            if source_name == "mainline/tools/r46h-card-toolchain":
                (source_path / "Cargo.toml").write_text(
                    "[workspace]\nresolver = \"2\"\n", encoding="utf-8"
                )
                (source_path / "Cargo.lock").write_text(
                    "# This file is automatically @generated by Cargo.\nversion = 4\n",
                    encoding="utf-8",
                )
            elif source_name == ".gitattributes":
                source_path.write_bytes((REPO_ROOT / source_name).read_bytes())
            else:
                source_path.parent.mkdir(parents=True, exist_ok=True)
                if source_name == "mainline/scripts/r46h_card_toolchain.py":
                    source_path.write_bytes(DRIVER_PATH.read_bytes())
                else:
                    source_path.write_text(f"fixture: {source_name}\n", encoding="utf-8")

        git_environment = os.environ.copy()
        git_environment.update(
            {
                "GIT_CONFIG_NOSYSTEM": "1",
                "GIT_CONFIG_GLOBAL": os.devnull,
                "GIT_AUTHOR_NAME": "R46H test",
                "GIT_AUTHOR_EMAIL": "r46h-test@example.invalid",
                "GIT_COMMITTER_NAME": "R46H test",
                "GIT_COMMITTER_EMAIL": "r46h-test@example.invalid",
            }
        )
        subprocess.run(
            ["git", "init", "--quiet", str(self.fake_repo)],
            check=True,
            env=git_environment,
        )
        subprocess.run(
            ["git", "-C", str(self.fake_repo), "add", "--"]
            + list(DRIVER.BUILD_SOURCE_PATHS),
            check=True,
            env=git_environment,
        )
        subprocess.run(
            [
                "git",
                "-C",
                str(self.fake_repo),
                "-c",
                "commit.gpgsign=false",
                "commit",
                "--quiet",
                "-m",
                "fixture",
            ],
            check=True,
            env=git_environment,
        )
        return self.layout()

    def publication_fixture(self) -> tuple[object, Path, Path, object]:
        layout = self.initialize_source_repository()
        DRIVER.prepare_layout(layout)
        work = layout.work_root / "publication-fixture"
        work.mkdir(mode=0o700)
        commit, tree = DRIVER.require_clean_source_scope(layout)
        source = DRIVER.capture_source_snapshot(layout, work, commit, tree)
        executable_name = "r46h-card.exe" if os.name == "nt" else "r46h-card"
        built = work / "target" / "release" / executable_name
        built.parent.mkdir(parents=True)
        built.write_bytes(b"first release binary\n")
        return layout, work, built, source

    def publish_fixture(
        self, layout: object, work: Path, built: Path, source: object
    ) -> tuple[Path, str]:
        def receipt(
            _layout: object,
            _source: object,
            executable_name: str,
            executable_sha256: str,
            executable_size: int,
            _commands: object,
            _environment: object,
            _gates: object,
            _storage_policy: str,
        ) -> dict[str, object]:
            return {
                "schema": DRIVER.BUILD_RECEIPT_SCHEMA,
                "status": "complete",
                "claim_scope": "first-party-source-and-output-integrity",
                "hermetic": False,
                "source": {
                    "cargo_lock_sha256": source.cargo_lock_sha256,
                    "driver_sha256": source.driver_sha256,
                    "file_count": source.file_count,
                    "git_commit": source.commit,
                    "git_tree": source.tree,
                    "scope": list(DRIVER.BUILD_SOURCE_PATHS),
                    "scope_clean_observed": True,
                    "snapshot_manifest_sha256": source.manifest_sha256,
                },
                "artifact": {
                    "path": executable_name,
                    "size": executable_size,
                    "sha256": executable_sha256,
                },
            }

        with mock.patch.object(DRIVER, "_publication_receipt", side_effect=receipt):
            return DRIVER.publish_release_generation(
                layout,
                work,
                built,
                source,
                {},
                {},
                [],
            )

    def refresh_generation_checksums(self, layout: object, generation: Path) -> None:
        executable_name = "r46h-card.exe" if os.name == "nt" else "r46h-card"
        names = sorted(
            {"BUILD-RECEIPT.json", "SOURCE-MANIFEST.json", executable_name},
            key=lambda item: item.encode("utf-8"),
        )
        sums = "".join(
            f"{DRIVER._sha256_file(generation / name)}  {name}\n" for name in names
        )
        (generation / "SHA256SUMS").write_text(sums, encoding="ascii")
        current_path = layout.release_dir / "CURRENT"
        current = DRIVER.json.loads(current_path.read_text(encoding="utf-8"))
        current["sha256sums_sha256"] = DRIVER._sha256_file(
            generation / "SHA256SUMS"
        )
        current_path.write_bytes(DRIVER._canonical_json(current))

    def test_default_cache_is_absolute_and_under_mainline_out(self) -> None:
        layout = self.layout()
        self.assertTrue(layout.cache_root.is_absolute())
        self.assertEqual(
            layout.cache_root,
            self.fake_repo
            / "mainline"
            / "out"
            / ".cache"
            / "r46h-card-toolchain",
        )

    def test_build_scope_pins_cross_platform_line_endings(self) -> None:
        self.assertIn(".gitattributes", DRIVER.BUILD_SOURCE_PATHS)
        self.assertIn("mainline/README.md", DRIVER.BUILD_SOURCE_PATHS)
        self.assertIn(
            "mainline/scripts/r46h_card_macos_readonly.py",
            DRIVER.BUILD_SOURCE_PATHS,
        )
        self.assertIn(
            "mainline/tests/test_r46h_card_macos_readonly.py",
            DRIVER.BUILD_SOURCE_PATHS,
        )
        build_source = inspect.getsource(DRIVER.command_build)
        self.assertIn('"python-macos-launcher-tests"', build_source)
        self.assertIn("test_r46h_card_macos_readonly.py", build_source)
        self.assertIn("_should_run_macos_launcher_tests()", build_source)
        attributes = (REPO_ROOT / ".gitattributes").read_text(encoding="utf-8")
        for rule in (
            ".gitattributes text eol=lf",
            ".github/workflows/ci.yml text eol=lf",
            "mainline/README.md text eol=lf",
            "mainline/scripts/r46h_card_toolchain.py text eol=lf",
            "mainline/scripts/r46h_card_macos_readonly.py text eol=lf",
            "mainline/tests/test_r46h_card_toolchain_build.py text eol=lf",
            "mainline/tests/test_r46h_card_macos_readonly.py text eol=lf",
            "mainline/tools/r46h-card-toolchain/**/*.rs text eol=lf",
            "mainline/tools/r46h-card-toolchain/**/*.toml text eol=lf",
            "mainline/tools/r46h-card-toolchain/**/Cargo.lock text eol=lf",
            "mainline/tools/r46h-card-toolchain/**/*.md text eol=lf",
            "mainline/tools/r46h-card-toolchain/**/*.json text eol=lf",
        ):
            with self.subTest(rule=rule):
                self.assertIn(rule, attributes)
        workflow = (
            REPO_ROOT / ".github" / "workflows" / "ci.yml"
        ).read_text(encoding="utf-8")
        self.assertIn("actions/checkout@v7", workflow)
        for command in (
            "python3 -B mainline/tests/test-project-docs.py",
            "cargo fmt --all -- --check",
            "cargo clippy --locked --workspace --all-targets -- -D warnings",
            "cargo test --locked -p r46h-card-core",
        ):
            with self.subTest(command=command):
                self.assertIn(command, workflow)
        self.assertNotIn("matrix:", workflow)
        self.assertNotIn("--allow-system-storage-for-ci", workflow)
        self.assertNotIn("test_r46h_card_toolchain_build.py", workflow)

    def test_macos_launcher_build_gate_is_host_specific(self) -> None:
        with mock.patch.object(DRIVER.sys, "platform", "darwin"):
            self.assertTrue(DRIVER._should_run_macos_launcher_tests())
        for platform in ("linux", "win32"):
            with self.subTest(platform=platform):
                with mock.patch.object(DRIVER.sys, "platform", platform):
                    self.assertFalse(DRIVER._should_run_macos_launcher_tests())

    def test_unsupported_python_version_fails_with_a_clear_error(self) -> None:
        with self.assertRaisesRegex(DRIVER.DriverError, "Python 3.10 or newer") as caught:
            DRIVER.require_supported_python((3, 9, 6))
        self.assertEqual(caught.exception.exit_code, DRIVER.EX_UNAVAILABLE)
        DRIVER.require_supported_python((3, 10, 0))

    def test_autocrlf_checkout_preserves_clean_source_scope(self) -> None:
        layout = self.initialize_source_repository()
        subprocess.run(
            ["git", "-C", str(self.fake_repo), "config", "core.autocrlf", "true"],
            check=True,
        )
        subprocess.run(
            ["git", "-C", str(self.fake_repo), "checkout-index", "--all", "--force"],
            check=True,
        )

        self.assertEqual(
            (self.fake_repo / "mainline" / "scripts" / "r46h_card_toolchain.py").read_bytes(),
            DRIVER_PATH.read_bytes(),
        )
        DRIVER.require_clean_source_scope(layout)

    def test_windows_snapshot_modes_remain_deletable(self) -> None:
        self.assertEqual(DRIVER._snapshot_file_mode(0o644, "nt"), 0o644)
        self.assertEqual(DRIVER._snapshot_file_mode(0o755, "nt"), 0o755)
        self.assertEqual(DRIVER._snapshot_file_mode(0o644, "posix"), 0o444)
        self.assertEqual(DRIVER._snapshot_file_mode(0o755, "posix"), 0o555)

    def test_relative_cache_override_is_rejected(self) -> None:
        with self.assertRaisesRegex(DRIVER.DriverError, "must be an absolute path"):
            DRIVER.make_layout("relative/cache", self.fake_repo)

    def test_cache_override_rejects_existing_symlink_component(self) -> None:
        actual = Path(self.temporary.name) / "actual"
        actual.mkdir()
        link = Path(self.temporary.name) / "link"
        self.directory_symlink_or_skip(link, actual)
        with self.assertRaisesRegex(DRIVER.DriverError, "unsafe symlink in cache path"):
            DRIVER.make_layout(str(link / "cache"), self.fake_repo)

    def test_cache_root_cannot_contain_repository(self) -> None:
        with self.assertRaisesRegex(DRIVER.DriverError, "may not contain the repository"):
            DRIVER.make_layout(str(self.fake_repo.parent), self.fake_repo)

    def test_cleanup_unlinks_symlink_without_following_it(self) -> None:
        layout = self.layout()
        DRIVER.prepare_layout(layout)
        sentinel = Path(self.temporary.name) / "sentinel"
        sentinel.mkdir()
        marker = sentinel / "keep"
        marker.write_text("keep", encoding="ascii")
        DRIVER.safe_remove_cache_child(layout, "target")
        self.directory_symlink_or_skip(layout.target_dir, sentinel)

        self.assertTrue(DRIVER.safe_remove_cache_child(layout, "target"))
        self.assertTrue(marker.is_file())
        self.assertFalse(layout.target_dir.exists())

    def test_recursive_cleanup_keeps_nested_symlink_target(self) -> None:
        layout = self.layout()
        DRIVER.prepare_layout(layout)
        nested = layout.target_dir / "nested"
        nested.mkdir()
        (nested / "object").write_text("object", encoding="ascii")
        sentinel = Path(self.temporary.name) / "outside"
        sentinel.mkdir()
        marker = sentinel / "keep"
        marker.write_text("keep", encoding="ascii")
        self.directory_symlink_or_skip(nested / "outside-link", sentinel)

        self.assertTrue(DRIVER.safe_remove_cache_child(layout, "target"))
        self.assertFalse(layout.target_dir.exists())
        self.assertTrue(marker.is_file())

    def test_cleanup_refuses_unknown_child(self) -> None:
        layout = self.layout()
        DRIVER.prepare_layout(layout)
        with self.assertRaisesRegex(DRIVER.DriverError, "unknown cache child"):
            DRIVER.safe_remove_cache_child(layout, "release")

    def test_cleanup_reports_concurrent_cache_change_without_retrying(self) -> None:
        layout = self.layout()
        DRIVER.prepare_layout(layout)
        with mock.patch.object(
            DRIVER,
            "_remove_tree_on_device",
            side_effect=OSError(66, "Directory not empty"),
        ):
            with self.assertRaisesRegex(
                DRIVER.DriverError, "cache changed during cleanup"
            ) as raised:
                DRIVER.safe_remove_cache_child(layout, "target")
        self.assertEqual(raised.exception.exit_code, DRIVER.EX_TEMPFAIL)
        self.assertTrue(layout.target_dir.is_dir())

    def test_cache_marker_binds_the_claimed_directory_identity(self) -> None:
        layout = self.layout()
        DRIVER.prepare_layout(layout)
        payload = DRIVER._validate_cache_marker(layout)
        payload["inode"] = int(payload["inode"]) + 1
        layout.marker_path.write_text(
            DRIVER.json.dumps(payload, sort_keys=True) + "\n", encoding="utf-8"
        )
        with self.assertRaisesRegex(DRIVER.DriverError, "marker mismatch for inode"):
            DRIVER._validate_cache_marker(layout)

    def test_private_work_directory_is_random_and_always_removed(self) -> None:
        layout = self.layout()
        DRIVER.prepare_layout(layout)
        work_path = None
        with self.assertRaisesRegex(RuntimeError, "synthetic failure"):
            with DRIVER.private_work_dir(layout, "test") as work:
                work_path = work
                if os.name != "nt":
                    self.assertEqual(stat_mode(work), 0o700)
                else:
                    self.assertTrue(work.is_dir())
                (work / "temporary").write_text("temporary", encoding="ascii")
                raise RuntimeError("synthetic failure")
        assert work_path is not None
        self.assertFalse(work_path.exists())

    def test_build_environment_moves_all_temporary_roots_to_cache(self) -> None:
        layout = self.layout()
        work = layout.work_root / "private"
        environment = DRIVER.build_environment(layout, work)
        self.assertEqual(environment["CARGO_HOME"], str(layout.cargo_home))
        self.assertEqual(environment["CARGO_TARGET_DIR"], str(layout.target_dir))
        self.assertEqual(environment["TMPDIR"], str(work))
        self.assertEqual(environment["TMP"], str(work))
        self.assertEqual(environment["TEMP"], str(work))
        self.assertEqual(environment["R46H_CARD_CACHE_ROOT"], str(layout.cache_root))
        self.assertEqual(environment["RUSTUP_AUTO_INSTALL"], "0")

    def test_build_environment_uses_private_target_and_drops_injection_flags(self) -> None:
        layout = self.layout()
        work = layout.work_root / "private"
        private_target = work / "target"
        rustc = Path(self.temporary.name) / "toolchain" / "rustc"
        injected = {
            "RUSTFLAGS": "-C linker=/tmp/not-a-linker",
            "CARGO_ENCODED_RUSTFLAGS": "-C\x1flinker=/tmp/not-a-linker",
            "RUSTC_WRAPPER": "/tmp/not-a-wrapper",
            "RUSTC_WORKSPACE_WRAPPER": "/tmp/not-a-wrapper",
            "CARGO_BUILD_TARGET": "attacker-target",
            "CARGO_TARGET_FAKE_LINKER": "/tmp/not-a-linker",
            "GIT_CONFIG_COUNT": "1",
            "GIT_CONFIG_KEY_0": "core.fsmonitor",
            "GIT_CONFIG_VALUE_0": "/tmp/not-a-hook",
            "R46H_CARGO_NET_OFFLINE": "false",
        }
        with mock.patch.dict(os.environ, injected, clear=False):
            environment = DRIVER.build_environment(
                layout,
                work,
                rustc,
                target_dir=private_target,
            )

        self.assertEqual(environment["CARGO_TARGET_DIR"], str(private_target))
        self.assertEqual(environment["RUSTC"], str(rustc))
        self.assertEqual(environment["CARGO_NET_OFFLINE"], "true")
        for name in injected.keys() - {"R46H_CARGO_NET_OFFLINE"}:
            self.assertNotIn(name, environment)

    def test_build_environment_rejects_shared_cargo_configuration(self) -> None:
        layout = self.layout()
        layout.cargo_home.mkdir(parents=True)
        (layout.cargo_home / "config.toml").write_text(
            "[build]\nrustflags = ['--cfg', 'injected']\n", encoding="utf-8"
        )

        with self.assertRaisesRegex(DRIVER.DriverError, "Cargo config|cargo config"):
            DRIVER.build_environment(
                layout,
                layout.work_root / "private",
                Path("/toolchain/rustc"),
                target_dir=layout.work_root / "private-target",
            )

    def test_private_cargo_home_copies_only_download_metadata(self) -> None:
        layout = self.layout()
        layout.cargo_home.mkdir(parents=True)
        archive = layout.cargo_home / "registry" / "cache" / "index" / "crate.crate"
        archive.parent.mkdir(parents=True)
        archive.write_bytes(b"archive")
        extracted = layout.cargo_home / "registry" / "src" / "index" / "crate" / "src.rs"
        extracted.parent.mkdir(parents=True)
        extracted.write_text("untrusted extracted source", encoding="utf-8")
        work = Path(self.temporary.name) / "cargo-private"
        work.mkdir()

        private_home = DRIVER.prepare_private_cargo_home(layout, work)

        self.assertEqual(
            (private_home / "registry" / "cache" / "index" / "crate.crate").read_bytes(),
            b"archive",
        )
        self.assertFalse((private_home / "registry" / "src").exists())

    def test_shared_cargo_home_prune_keeps_only_archives_and_index(self) -> None:
        layout = self.layout()
        DRIVER.prepare_layout(layout)
        archive = layout.cargo_home / "registry" / "cache" / "index" / "crate.crate"
        archive.parent.mkdir(parents=True)
        archive.write_bytes(b"archive")
        index = layout.cargo_home / "registry" / "index" / "index" / "config.json"
        index.parent.mkdir(parents=True)
        index.write_text("{}\n", encoding="utf-8")
        (layout.cargo_home / "registry" / "CACHEDIR.TAG").write_text(
            "Signature: 8a477f597d28d172789f06886806bc55\n",
            encoding="utf-8",
        )
        extracted = layout.cargo_home / "registry" / "src" / "index" / "crate" / "src.rs"
        extracted.parent.mkdir(parents=True)
        extracted.write_text("disposable source\n", encoding="utf-8")
        git_checkout = layout.cargo_home / "git" / "checkouts" / "crate" / "source.rs"
        git_checkout.parent.mkdir(parents=True)
        git_checkout.write_text("disposable checkout\n", encoding="utf-8")
        (layout.cargo_home / ".global-cache").write_bytes(b"state")

        DRIVER.prune_shared_cargo_home(layout)

        self.assertEqual(archive.read_bytes(), b"archive")
        self.assertEqual(index.read_text(encoding="utf-8"), "{}\n")
        self.assertTrue((layout.cargo_home / "registry" / "CACHEDIR.TAG").is_file())
        self.assertEqual(
            {entry.name for entry in layout.cargo_home.iterdir()},
            {"registry"},
        )
        self.assertEqual(
            {entry.name for entry in (layout.cargo_home / "registry").iterdir()},
            {"cache", "index", "CACHEDIR.TAG"},
        )

    def test_shared_cargo_home_prune_rejects_replaced_registry(self) -> None:
        layout = self.layout()
        DRIVER.prepare_layout(layout)
        replacement = Path(self.temporary.name) / "registry-replacement"
        replacement.mkdir()
        self.directory_symlink_or_skip(layout.cargo_home / "registry", replacement)

        with self.assertRaisesRegex(DRIVER.DriverError, "unsafe shared Cargo registry"):
            DRIVER.prune_shared_cargo_home(layout)

    def test_shared_cargo_home_prune_preserves_and_rejects_config(self) -> None:
        layout = self.layout()
        DRIVER.prepare_layout(layout)
        config = layout.cargo_home / "config.toml"
        config.write_text("[build]\nrustflags = ['--cfg', 'injected']\n", encoding="utf-8")

        with self.assertRaisesRegex(DRIVER.DriverError, "Cargo config"):
            DRIVER.prune_shared_cargo_home(layout)

        self.assertTrue(config.is_file())

    def test_shared_cargo_home_prune_rejects_config_case_alias_before_mutation(self) -> None:
        layout = self.layout()
        DRIVER.prepare_layout(layout)
        disposable = layout.cargo_home / ".global-cache"
        disposable.write_bytes(b"must remain on failed preflight")
        config = layout.cargo_home / "CONFIG.TOML"
        config.write_text("[build]\nrustflags = ['--cfg', 'injected']\n", encoding="utf-8")

        with self.assertRaisesRegex(DRIVER.DriverError, "Cargo config"):
            DRIVER.prune_shared_cargo_home(layout)

        self.assertTrue(config.is_file())
        self.assertEqual(disposable.read_bytes(), b"must remain on failed preflight")

    def test_shared_cargo_home_prune_rejects_retained_name_case_alias(self) -> None:
        layout = self.layout()
        DRIVER.prepare_layout(layout)
        registry = layout.cargo_home / "registry"
        registry.mkdir()
        alias = registry / "CACHE"
        alias.mkdir()

        with self.assertRaisesRegex(DRIVER.DriverError, "noncanonical retained"):
            DRIVER.prune_shared_cargo_home(layout)

        self.assertTrue(alias.is_dir())

    def test_shared_cargo_home_prune_rejects_cross_device_root(self) -> None:
        layout = self.layout()
        DRIVER.prepare_layout(layout)
        original_stat = Path.stat

        def cross_device_stat(path: Path, *args: object, **kwargs: object) -> os.stat_result:
            metadata = original_stat(path, *args, **kwargs)
            if path == layout.cargo_home and kwargs.get("follow_symlinks") is False:
                values = list(metadata)
                values[2] = metadata.st_dev + 1
                return os.stat_result(values)
            return metadata

        with mock.patch.object(Path, "stat", cross_device_stat):
            with self.assertRaisesRegex(DRIVER.DriverError, "unsafe shared Cargo home"):
                DRIVER.prune_shared_cargo_home(layout)

    def test_download_cache_rejects_links_and_cross_device_entries(self) -> None:
        layout = self.layout()
        DRIVER.prepare_layout(layout)
        boundary = DRIVER._mount_boundary(layout.cache_root, directory=True)
        cache = layout.cargo_home / "registry" / "cache"
        cache.mkdir(parents=True)
        outside = Path(self.temporary.name) / "outside-cache"
        outside.mkdir()
        link = cache / "linked"
        self.directory_symlink_or_skip(link, outside)

        with self.assertRaisesRegex(DRIVER.DriverError, "contains a link"):
            DRIVER._validate_download_cache_tree(cache, boundary)

        dangling = layout.cargo_home / "registry" / "dangling-cache"
        self.directory_symlink_or_skip(dangling, Path(self.temporary.name) / "missing")
        with self.assertRaisesRegex(DRIVER.DriverError, "unsafe Cargo download cache"):
            DRIVER._validate_download_cache_tree(
                dangling,
                boundary,
            )

        link.unlink()
        payload = cache / "crate.crate"
        payload.write_bytes(b"archive")
        original_stat = Path.stat

        def cross_device_stat(path: Path, *args: object, **kwargs: object) -> os.stat_result:
            metadata = original_stat(path, *args, **kwargs)
            if path == payload:
                values = list(metadata)
                values[2] = metadata.st_dev + 1
                return os.stat_result(values)
            return metadata

        with mock.patch.object(Path, "stat", cross_device_stat):
            with self.assertRaisesRegex(DRIVER.DriverError, "crosses a filesystem"):
                DRIVER._validate_download_cache_tree(
                    cache,
                    boundary,
                )

    def test_mount_identity_parser_is_strict(self) -> None:
        self.assertEqual(
            DRIVER._parse_linux_mount_id("pos:\t0\nflags:\t0100000\nmnt_id:\t42\n"),
            "42",
        )
        for payload in (
            "pos:\t0\n",
            "mnt_id:\t0\n",
            "mnt_id:\tnot-a-number\n",
            "mnt_id:\t42\nmnt_id:\t43\n",
        ):
            with self.subTest(payload=payload):
                with self.assertRaisesRegex(DRIVER.DriverError, "mount identity"):
                    DRIVER._parse_linux_mount_id(payload)

    def test_same_device_nested_mount_is_rejected_before_copy_or_cleanup(self) -> None:
        layout = self.layout()
        DRIVER.prepare_layout(layout)
        boundary = DRIVER._mount_boundary(layout.cache_root, directory=True)
        foreign = DRIVER.MountBoundary(boundary.device, boundary.token + "-foreign")
        root = layout.cargo_home / "registry" / "cache"
        nested = root / "same-device-bind"
        nested.mkdir(parents=True)
        sentinel = nested / "must-remain"
        sentinel.write_bytes(b"sentinel")
        real_mount_boundary = DRIVER._mount_boundary

        def synthetic_boundary(path: Path, *, directory: bool) -> object:
            if path == nested:
                return foreign
            return real_mount_boundary(path, directory=directory)

        with mock.patch.object(
            DRIVER,
            "_mount_boundary",
            side_effect=synthetic_boundary,
        ):
            with self.assertRaisesRegex(DRIVER.DriverError, "mount boundary"):
                DRIVER._validate_download_cache_tree(root, boundary)
            with self.assertRaisesRegex(DRIVER.DriverError, "mount boundary"):
                DRIVER._validate_removable_cache_tree(root, boundary)
            with self.assertRaisesRegex(DRIVER.DriverError, "mount boundary"):
                DRIVER._remove_tree_on_device(root, boundary)

        self.assertEqual(sentinel.read_bytes(), b"sentinel")
        self.assertTrue(root.is_dir())

    @unittest.skipIf(os.name == "nt", "POSIX descriptor-copy coverage")
    def test_fd_copy_rejects_same_device_nested_mount(self) -> None:
        layout = self.layout()
        DRIVER.prepare_layout(layout)
        boundary = DRIVER._mount_boundary(layout.cache_root, directory=True)
        foreign = DRIVER.MountBoundary(boundary.device, boundary.token + "-foreign")
        source = layout.cargo_home / "registry" / "cache"
        nested = source / "same-device-bind"
        nested.mkdir(parents=True)
        (nested / "must-not-copy").write_bytes(b"sentinel")
        destination = Path(self.temporary.name) / "copied-cache"
        nested_identity = (nested.stat().st_dev, nested.stat().st_ino)
        real_descriptor_boundary = DRIVER._descriptor_mount_boundary

        def synthetic_descriptor_boundary(descriptor: int) -> object:
            metadata = os.fstat(descriptor)
            if (metadata.st_dev, metadata.st_ino) == nested_identity:
                return foreign
            return real_descriptor_boundary(descriptor)

        with mock.patch.object(
            DRIVER,
            "_descriptor_mount_boundary",
            side_effect=synthetic_descriptor_boundary,
        ):
            with self.assertRaisesRegex(DRIVER.DriverError, "changed|mount boundary"):
                DRIVER._copy_download_cache_tree(source, destination, boundary)

        self.assertFalse((destination / "same-device-bind" / "must-not-copy").exists())
        self.assertEqual((nested / "must-not-copy").read_bytes(), b"sentinel")

    def test_windows_reparse_attribute_must_be_observable(self) -> None:
        class MetadataWithoutFileAttributes:
            st_mode = stat.S_IFDIR | 0o700
            st_dev = 7
            st_ino = 9

        metadata = MetadataWithoutFileAttributes()
        with mock.patch.object(DRIVER.os, "name", "nt"):
            with self.assertRaisesRegex(DRIVER.DriverError, "reparse-point attributes"):
                DRIVER._metadata_is_link_or_reparse(metadata)  # type: ignore[arg-type]
        if os.name != "nt":
            self.assertFalse(
                DRIVER._metadata_is_link_or_reparse(metadata)  # type: ignore[arg-type]
            )

        invalid = mock.Mock(spec=os.stat_result)
        invalid.st_mode = stat.S_IFDIR | 0o700
        invalid.st_file_attributes = mock.Mock()
        with self.assertRaisesRegex(DRIVER.DriverError, "reparse-point attributes"):
            DRIVER._metadata_is_link_or_reparse(invalid)

    def test_clean_source_scope_allows_untracked_files_outside_scope(self) -> None:
        layout = self.initialize_source_repository()
        untracked = self.fake_repo / ".tmp-r46h-user-owned"
        untracked.write_text("not a build input\n", encoding="utf-8")

        DRIVER.require_clean_source_scope(layout)

        tracked = self.fake_repo / "mainline" / "tools" / "r46h-card-toolchain" / "Cargo.toml"
        tracked.write_text("[workspace]\n# dirty\n", encoding="utf-8")
        with self.assertRaisesRegex(DRIVER.DriverError, "unstaged|tracked|dirty|clean"):
            DRIVER.require_clean_source_scope(layout)

    def test_clean_source_scope_rejects_untracked_files_inside_scope(self) -> None:
        layout = self.initialize_source_repository()
        untracked = (
            self.fake_repo
            / "mainline"
            / "tools"
            / "r46h-card-toolchain"
            / "local-source.rs"
        )
        untracked.write_text("must not enter strict build\n", encoding="utf-8")

        with self.assertRaisesRegex(DRIVER.DriverError, "untracked|dirty|clean"):
            DRIVER.require_clean_source_scope(layout)

    def test_clean_source_scope_rejects_staged_changes(self) -> None:
        layout = self.initialize_source_repository()
        tracked = self.fake_repo / "mainline" / "tools" / "r46h-card-toolchain" / "Cargo.toml"
        tracked.write_text("[workspace]\n# staged\n", encoding="utf-8")
        subprocess.run(
            [
                "git",
                "-C",
                str(self.fake_repo),
                "add",
                "--",
                "mainline/tools/r46h-card-toolchain/Cargo.toml",
            ],
            check=True,
        )

        with self.assertRaisesRegex(DRIVER.DriverError, "staged|dirty|clean"):
            DRIVER.require_clean_source_scope(layout)

    def test_git_replace_objects_cannot_rewrite_the_head_source_tree(self) -> None:
        layout = self.initialize_source_repository()
        original_commit = subprocess.run(
            ["git", "-C", str(self.fake_repo), "rev-parse", "HEAD"],
            check=True,
            stdout=subprocess.PIPE,
            text=True,
        ).stdout.strip()
        cargo = (
            self.fake_repo
            / "mainline"
            / "tools"
            / "r46h-card-toolchain"
            / "Cargo.toml"
        )
        cargo.write_text("[workspace]\nresolver = \"3\"\n", encoding="utf-8")
        subprocess.run(
            ["git", "-C", str(self.fake_repo), "add", "--", str(cargo)],
            check=True,
        )
        subprocess.run(
            [
                "git",
                "-C",
                str(self.fake_repo),
                "-c",
                "user.name=R46H test",
                "-c",
                "user.email=r46h-test@example.invalid",
                "-c",
                "commit.gpgsign=false",
                "commit",
                "--quiet",
                "-m",
                "replacement fixture",
            ],
            check=True,
        )
        replacement_commit = subprocess.run(
            ["git", "-C", str(self.fake_repo), "rev-parse", "HEAD"],
            check=True,
            stdout=subprocess.PIPE,
            text=True,
        ).stdout.strip()
        subprocess.run(
            ["git", "-C", str(self.fake_repo), "replace", original_commit, replacement_commit],
            check=True,
        )
        subprocess.run(
            ["git", "-C", str(self.fake_repo), "reset", "--hard", original_commit],
            check=True,
            stdout=subprocess.DEVNULL,
        )

        rewritten_tree = subprocess.run(
            ["git", "-C", str(self.fake_repo), "rev-parse", "HEAD^{tree}"],
            check=True,
            stdout=subprocess.PIPE,
            text=True,
        ).stdout.strip()
        true_tree = subprocess.run(
            [
                "git",
                "--no-replace-objects",
                "-C",
                str(self.fake_repo),
                "rev-parse",
                "HEAD^{tree}",
            ],
            check=True,
            stdout=subprocess.PIPE,
            text=True,
        ).stdout.strip()
        self.assertNotEqual(rewritten_tree, true_tree)
        self.assertEqual(DRIVER._git_environment()["GIT_NO_REPLACE_OBJECTS"], "1")
        with self.assertRaisesRegex(DRIVER.DriverError, "staged|unstaged|clean"):
            DRIVER.require_clean_source_scope(layout)

    def test_source_snapshot_contains_only_committed_build_inputs(self) -> None:
        layout = self.initialize_source_repository()
        untracked = self.fake_repo / ".tmp-r46h-user-owned"
        untracked.write_text("must not enter snapshot\n", encoding="utf-8")
        work = Path(self.temporary.name) / "snapshot-work"
        work.mkdir()

        commit, tree = DRIVER.require_clean_source_scope(layout)
        snapshot = DRIVER.capture_source_snapshot(layout, work, commit, tree)
        snapshot_cargo = (
            snapshot.root
            / "mainline"
            / "tools"
            / "r46h-card-toolchain"
            / "Cargo.toml"
        )
        live_cargo = (
            self.fake_repo
            / "mainline"
            / "tools"
            / "r46h-card-toolchain"
            / "Cargo.toml"
        )
        live_cargo.write_text("[workspace]\n# changed after capture\n", encoding="utf-8")

        self.assertEqual(
            snapshot_cargo.read_text(encoding="utf-8"),
            "[workspace]\nresolver = \"2\"\n",
        )
        self.assertFalse((snapshot.root / ".tmp-r46h-user-owned").exists())
        self.assertTrue(snapshot.manifest_path.is_file())
        self.assertFalse((work / "source.tar").exists())
        DRIVER.validate_source_snapshot(snapshot)
        snapshot_cargo.chmod(0o644)
        snapshot_cargo.write_text("tampered snapshot\n", encoding="utf-8")
        with self.assertRaisesRegex(DRIVER.DriverError, "changed during build"):
            DRIVER.validate_source_snapshot(snapshot)

    def test_source_snapshot_rejects_committed_symlinks(self) -> None:
        layout = self.initialize_source_repository()
        link = (
            self.fake_repo
            / "mainline"
            / "tools"
            / "r46h-card-toolchain"
            / "linked-source"
        )
        try:
            link.symlink_to("Cargo.toml")
        except (NotImplementedError, OSError) as error:
            self.skipTest(f"symlink fixture is unavailable: {error}")
        subprocess.run(
            [
                "git",
                "-C",
                str(self.fake_repo),
                "add",
                "--",
                "mainline/tools/r46h-card-toolchain/linked-source",
            ],
            check=True,
        )
        subprocess.run(
            [
                "git",
                "-C",
                str(self.fake_repo),
                "-c",
                "user.name=R46H test",
                "-c",
                "user.email=r46h-test@example.invalid",
                "-c",
                "commit.gpgsign=false",
                "commit",
                "--quiet",
                "-m",
                "symlink fixture",
            ],
            check=True,
        )

        work = Path(self.temporary.name) / "symlink-snapshot-work"
        work.mkdir()
        commit, tree = DRIVER.require_clean_source_scope(layout)
        with self.assertRaisesRegex(DRIVER.DriverError, "symlink|link|unsupported"):
            DRIVER.capture_source_snapshot(layout, work, commit, tree)

    def test_release_publication_switches_current_to_complete_generation(self) -> None:
        layout, work, built, source = self.publication_fixture()

        generation, digest = self.publish_fixture(layout, work, built, source)

        self.assertEqual(DRIVER.validate_release_generation(layout), generation)
        self.assertEqual(digest, DRIVER._sha256_file(generation / built.name))
        self.assertEqual(
            {entry.name for entry in generation.iterdir()},
            {
                "BUILD-RECEIPT.json",
                "SHA256SUMS",
                "SOURCE-MANIFEST.json",
                built.name,
            },
        )
        current = DRIVER.json.loads(
            (layout.release_dir / "CURRENT").read_text(encoding="utf-8")
        )
        self.assertEqual(current["generation"], generation.name)
        self.assertFalse((work / "release-generation").exists())

    def test_release_validator_rejects_tampering_and_member_set_changes(self) -> None:
        layout, work, built, source = self.publication_fixture()
        generation, _digest = self.publish_fixture(layout, work, built, source)

        for name in (
            built.name,
            "BUILD-RECEIPT.json",
            "SOURCE-MANIFEST.json",
            "SHA256SUMS",
        ):
            with self.subTest(member=name):
                member = generation / name
                original = member.read_bytes()
                member.write_bytes(original + b"tampered\n")
                with self.assertRaises(DRIVER.DriverError):
                    DRIVER.validate_release_generation(layout)
                member.write_bytes(original)

        extra = generation / "unexpected"
        extra.write_text("unexpected\n", encoding="utf-8")
        with self.assertRaisesRegex(DRIVER.DriverError, "file set mismatch"):
            DRIVER.validate_release_generation(layout)
        extra.unlink()

        missing = generation / "SOURCE-MANIFEST.json"
        original = missing.read_bytes()
        missing.unlink()
        with self.assertRaisesRegex(DRIVER.DriverError, "file set mismatch"):
            DRIVER.validate_release_generation(layout)
        missing.write_bytes(original)

    def test_release_validator_rejects_current_escape_and_root_mismatch(self) -> None:
        layout, work, built, source = self.publication_fixture()
        self.publish_fixture(layout, work, built, source)
        current_path = layout.release_dir / "CURRENT"
        current = DRIVER.json.loads(current_path.read_text(encoding="utf-8"))

        escaped = dict(current)
        escaped["generation"] = "../outside"
        current_path.write_bytes(DRIVER._canonical_json(escaped))
        with self.assertRaisesRegex(DRIVER.DriverError, "generation name is invalid"):
            DRIVER.validate_release_generation(layout)

        wrong_root = dict(current)
        wrong_root["sha256sums_sha256"] = "0" * 64
        current_path.write_bytes(DRIVER._canonical_json(wrong_root))
        with self.assertRaisesRegex(DRIVER.DriverError, "checksum root mismatch"):
            DRIVER.validate_release_generation(layout)

    def test_release_validator_rejects_semantically_mixed_source_closure(self) -> None:
        layout, work, built, source = self.publication_fixture()
        generation, _digest = self.publish_fixture(layout, work, built, source)
        manifest_path = generation / "SOURCE-MANIFEST.json"
        manifest = DRIVER.json.loads(manifest_path.read_text(encoding="utf-8"))
        manifest["git_commit"] = "5" * 40
        manifest_path.write_bytes(DRIVER._canonical_json(manifest))
        self.refresh_generation_checksums(layout, generation)

        with self.assertRaisesRegex(DRIVER.DriverError, "source identity"):
            DRIVER.validate_release_generation(layout)

    def test_release_validator_rejects_self_consistent_manifest_record_forgery(self) -> None:
        layout, work, built, source = self.publication_fixture()
        generation, _digest = self.publish_fixture(layout, work, built, source)
        manifest_path = generation / "SOURCE-MANIFEST.json"
        receipt_path = generation / "BUILD-RECEIPT.json"
        manifest = DRIVER.json.loads(manifest_path.read_text(encoding="utf-8"))
        manifest["files"][0]["size"] += 1
        manifest["files"][0]["sha256"] = "a" * 64
        manifest_path.write_bytes(DRIVER._canonical_json(manifest))
        receipt = DRIVER.json.loads(receipt_path.read_text(encoding="utf-8"))
        receipt["source"]["snapshot_manifest_sha256"] = DRIVER._sha256_file(
            manifest_path
        )
        receipt_path.write_bytes(DRIVER._canonical_json(receipt))
        self.refresh_generation_checksums(layout, generation)

        with self.assertRaisesRegex(DRIVER.DriverError, "current Git tree"):
            DRIVER.validate_release_generation(layout)

    def test_release_validator_rejects_fully_resigned_fake_source_identity(self) -> None:
        layout, work, built, source = self.publication_fixture()
        generation, _digest = self.publish_fixture(layout, work, built, source)
        manifest_path = generation / "SOURCE-MANIFEST.json"
        receipt_path = generation / "BUILD-RECEIPT.json"
        manifest = DRIVER.json.loads(manifest_path.read_text(encoding="utf-8"))
        manifest["git_commit"] = "5" * 40
        manifest["git_tree"] = "6" * 40
        manifest_path.write_bytes(DRIVER._canonical_json(manifest))
        receipt = DRIVER.json.loads(receipt_path.read_text(encoding="utf-8"))
        receipt["source"]["git_commit"] = manifest["git_commit"]
        receipt["source"]["git_tree"] = manifest["git_tree"]
        receipt["source"]["snapshot_manifest_sha256"] = DRIVER._sha256_file(
            manifest_path
        )
        receipt_path.write_bytes(DRIVER._canonical_json(receipt))
        forged_name = (
            f"build-{'5' * 12}-"
            f"{DRIVER._sha256_file(generation / built.name)[:12]}-deadbeef"
        )
        forged_generation = generation.parent / forged_name
        generation.rename(forged_generation)
        current_path = layout.release_dir / "CURRENT"
        current = DRIVER.json.loads(current_path.read_text(encoding="utf-8"))
        current["generation"] = forged_name
        current_path.write_bytes(DRIVER._canonical_json(current))
        self.refresh_generation_checksums(layout, forged_generation)

        with self.assertRaisesRegex(DRIVER.DriverError, "current clean HEAD"):
            DRIVER.validate_release_generation(layout)

    def test_release_validator_rejects_linked_release_ancestry(self) -> None:
        layout, work, built, source = self.publication_fixture()
        self.publish_fixture(layout, work, built, source)
        components = (
            layout.out_root / "r46h-card-toolchain",
            layout.release_dir.parent,
        )
        for index, component in enumerate(components):
            with self.subTest(component=component.name):
                external = Path(self.temporary.name) / f"release-component-{index}"
                component.rename(external)
                try:
                    component.symlink_to(external, target_is_directory=True)
                except (NotImplementedError, OSError) as error:
                    external.rename(component)
                    self.skipTest(f"directory symlink fixture is unavailable: {error}")
                try:
                    with self.assertRaisesRegex(DRIVER.DriverError, "release path"):
                        DRIVER.validate_release_generation(layout)
                finally:
                    component.unlink()
                    external.rename(component)

    def test_release_validator_rejects_generation_identity_and_directory_link(self) -> None:
        layout, work, built, source = self.publication_fixture()
        generation, _digest = self.publish_fixture(layout, work, built, source)
        builds = generation.parent
        wrong_name = (
            f"build-{'0' * 12}-"
            f"{DRIVER._sha256_file(generation / built.name)[:12]}-deadbeef"
        )
        wrong_generation = builds / wrong_name
        generation.rename(wrong_generation)
        current = DRIVER.json.loads(
            (layout.release_dir / "CURRENT").read_text(encoding="utf-8")
        )
        current["generation"] = wrong_name
        (layout.release_dir / "CURRENT").write_bytes(DRIVER._canonical_json(current))
        with self.assertRaisesRegex(DRIVER.DriverError, "generation identity"):
            DRIVER.validate_release_generation(layout)

        wrong_generation.rename(generation)
        current["generation"] = generation.name
        (layout.release_dir / "CURRENT").write_bytes(DRIVER._canonical_json(current))
        external = Path(self.temporary.name) / "external-generation"
        generation.rename(external)
        try:
            generation.symlink_to(external, target_is_directory=True)
        except (NotImplementedError, OSError) as error:
            external.rename(generation)
            self.skipTest(f"directory symlink fixture is unavailable: {error}")
        with self.assertRaisesRegex(DRIVER.DriverError, "release generation"):
            DRIVER.validate_release_generation(layout)

    def test_failed_current_replace_keeps_previous_generation_selected(self) -> None:
        layout, work, built, source = self.publication_fixture()
        previous, _digest = self.publish_fixture(layout, work, built, source)
        built.write_bytes(b"second release binary\n")
        real_replace = DRIVER.os.replace

        def fail_current_replace(source_path: object, destination_path: object) -> None:
            if Path(destination_path) == layout.release_dir / "CURRENT":
                raise OSError("synthetic CURRENT replacement failure")
            real_replace(source_path, destination_path)

        with mock.patch.object(DRIVER.os, "replace", side_effect=fail_current_replace):
            with self.assertRaisesRegex(OSError, "synthetic CURRENT"):
                self.publish_fixture(layout, work, built, source)

        self.assertEqual(DRIVER.validate_release_generation(layout), previous)
        self.assertEqual(
            sorted(path.name for path in (layout.release_dir / "builds").iterdir()),
            [previous.name],
        )
        self.assertFalse(any(layout.release_dir.glob(".CURRENT.*.tmp")))

    def test_successful_republication_removes_obsolete_generation(self) -> None:
        layout, work, built, source = self.publication_fixture()
        previous, _digest = self.publish_fixture(layout, work, built, source)
        built.write_bytes(b"second release binary\n")

        current, _digest = self.publish_fixture(layout, work, built, source)

        self.assertNotEqual(current, previous)
        self.assertFalse(previous.exists())
        self.assertEqual(DRIVER.validate_release_generation(layout), current)

    def test_macos_internal_storage_is_rejected(self) -> None:
        layout = self.layout()
        identity = DRIVER.MacStorageIdentity(Path("/"), True, "disk0")
        with mock.patch.object(DRIVER, "query_macos_storage_identity", return_value=identity):
            with self.assertRaisesRegex(DRIVER.DriverError, "internal macOS disk"):
                DRIVER.validate_storage(layout, platform_name="darwin")

    def test_macos_storage_identity_queries_the_resolved_mount_point(self) -> None:
        nested = Path("/Volumes/Ju/project/evidence")
        mount_point = Path("/Volumes/Ju")
        observed: list[list[str]] = []

        def runner(arguments: list[str], **_kwargs: object) -> subprocess.CompletedProcess[bytes]:
            observed.append(arguments)
            payload = DRIVER.plistlib.dumps(
                {
                    "MountPoint": str(mount_point),
                    "Internal": False,
                    "ParentWholeDisk": "disk7",
                    "APFSPhysicalStores": [{"APFSPhysicalStore": "disk6s2"}],
                }
            )
            return subprocess.CompletedProcess(arguments, 0, payload, b"")

        with mock.patch.object(DRIVER.Path, "is_file", return_value=True), mock.patch.object(
            DRIVER, "_mount_point", return_value=mount_point
        ):
            identity = DRIVER.query_macos_storage_identity(nested, runner=runner)

        self.assertEqual(observed[0][-1], str(mount_point))
        self.assertEqual(identity.mount_point, mount_point)
        self.assertFalse(identity.internal)
        self.assertEqual(identity.physical_id, "disk6")

    def test_macos_storage_identity_rejects_ambiguous_apfs_physical_stores(self) -> None:
        mount_point = Path("/Volumes/Ju")

        def runner(arguments: list[str], **_kwargs: object) -> subprocess.CompletedProcess[bytes]:
            payload = DRIVER.plistlib.dumps(
                {
                    "MountPoint": str(mount_point),
                    "Internal": False,
                    "ParentWholeDisk": "disk7",
                    "APFSPhysicalStores": [
                        {"APFSPhysicalStore": "disk6s2"},
                        {"APFSPhysicalStore": "disk8s2"},
                    ],
                }
            )
            return subprocess.CompletedProcess(arguments, 0, payload, b"")

        with mock.patch.object(DRIVER.Path, "is_file", return_value=True), mock.patch.object(
            DRIVER, "_mount_point", return_value=mount_point
        ):
            identity = DRIVER.query_macos_storage_identity(mount_point, runner=runner)

        self.assertFalse(identity.internal)
        self.assertIsNone(identity.physical_id)

    def test_system_storage_override_requires_explicit_ci(self) -> None:
        layout = self.layout()
        with mock.patch.dict(os.environ, {"CI": ""}, clear=False):
            with self.assertRaisesRegex(DRIVER.DriverError, "restricted to.*CI"):
                DRIVER.validate_storage(
                    layout,
                    platform_name="linux",
                    allow_system_storage_for_ci=True,
                )
        with mock.patch.dict(os.environ, {"CI": "true"}, clear=False):
            DRIVER.validate_storage(
                layout,
                platform_name="linux",
                allow_system_storage_for_ci=True,
            )

    def test_build_and_clean_contend_on_the_same_lock(self) -> None:
        cache = Path(self.temporary.name) / "shared-cache"
        layout = DRIVER.make_layout(str(cache))
        DRIVER.validate_storage(layout, platform_name="linux")
        DRIVER._prepare_cache_identity(layout)
        for path in (
            layout.cargo_home,
            layout.target_dir,
            layout.work_root,
            layout.state_root,
        ):
            DRIVER._mkdir_private(path)
        command = [
            sys.executable,
            str(DRIVER_PATH),
            "clean",
            "--cache-root",
            str(cache),
            "--lock-timeout",
            "0.1",
        ]
        with DRIVER.operation_lock(layout, 1.0):
            result = subprocess.run(
                command,
                cwd=REPO_ROOT,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                check=False,
            )
        self.assertEqual(result.returncode, DRIVER.EX_TEMPFAIL, result.stderr)
        self.assertIn("timed out waiting for the build/clean lock", result.stderr)

    def test_argument_parser_accepts_wrapper_style_cache_option(self) -> None:
        parser = DRIVER.make_parser()
        cache = str(Path(self.temporary.name) / "cache")
        args = parser.parse_args(["build", "--cache-root", cache, "--online"])
        self.assertEqual(args.cache_root, cache)
        self.assertTrue(args.online)


class CardToolchainProfileFixtureTests(unittest.TestCase):
    V2_PROFILE = (
        REPO_ROOT
        / "mainline"
        / "tools"
        / "r46h-card-toolchain"
        / "examples"
        / "profiles"
        / "hl-r46h-v22-g92-62534975488-v2.json"
    )
    V2_SCHEMA = (
        REPO_ROOT
        / "mainline"
        / "tools"
        / "r46h-card-toolchain"
        / "schemas"
        / "profile-v2.schema.json"
    )
    WRITE_PLAN_SCHEMA = (
        REPO_ROOT
        / "mainline"
        / "tools"
        / "r46h-card-toolchain"
        / "schemas"
        / "write-plan-v2.schema.json"
    )

    def load_json(self, path: Path) -> object:
        with path.open("r", encoding="utf-8") as handle:
            return json.load(handle)

    def test_fast_card_v2_fixture_has_the_exact_expected_identity(self) -> None:
        expected = {
            "format_version": 2,
            "profile_id": "hl-r46h-v22-g92-62534975488-v2",
            "target": "HL-R46H-V22",
            "whole_size": 62534975488,
            "sector_size": 512,
            "partition_scheme": "mbr",
            "prefix": {
                "size": 16777216,
                "sha256": "3fe2feb9cc89ce5f01603199bfc8b715875708a9acc61bfc68b4821e1d8a5da3",
            },
            "partitions": [
                {
                    "role": "boot",
                    "number": 1,
                    "offset": 16777216,
                    "size": 117440512,
                    "mbr": {"bootable": False, "type_code": 11},
                    "filesystem": "fat32",
                    "identifiers": {
                        "volume_uuid": "575BC58C-96FA-3E4F-958B-7A30D5210C3D",
                    },
                },
                {
                    "role": "root",
                    "number": 2,
                    "offset": 134217728,
                    "size": 10716877312,
                    "mbr": {"bootable": False, "type_code": 131},
                    "filesystem": "ext4",
                    "identifiers": {
                        "partuuid": "c9f931c9-02",
                    },
                },
                {
                    "role": "easyroms",
                    "number": 3,
                    "offset": 10851095040,
                    "size": 51683880448,
                    "mbr": {"bootable": False, "type_code": 7},
                    "filesystem": "exfat",
                    "identifiers": {
                        "volume_uuid": "75495362-8048-4A4A-ACB7-625349754881",
                    },
                },
            ],
        }

        self.assertEqual(self.load_json(self.V2_PROFILE), expected)

    def test_fast_card_v2_fixture_matches_the_strict_schema_shape(self) -> None:
        profile = self.load_json(self.V2_PROFILE)
        schema = self.load_json(self.V2_SCHEMA)
        self.assertFalse(schema["additionalProperties"])
        self.assertEqual(set(profile), set(schema["required"]))
        self.assertEqual(
            profile["format_version"],
            schema["properties"]["format_version"]["const"],
        )
        self.assertIn(
            profile["partition_scheme"],
            schema["properties"]["partition_scheme"]["enum"],
        )
        self.assertIsNotNone(
            re.fullmatch(schema["$defs"]["id"]["pattern"], profile["profile_id"])
        )
        self.assertIsNotNone(
            re.fullmatch(
                schema["$defs"]["sha256"]["pattern"], profile["prefix"]["sha256"]
            )
        )

        partition_schema = schema["$defs"]["partition"]
        allowed_partition_fields = set(partition_schema["properties"])
        required_partition_fields = set(partition_schema["required"])
        self.assertFalse(partition_schema["additionalProperties"])
        for partition in profile["partitions"]:
            self.assertTrue(required_partition_fields <= set(partition))
            self.assertTrue(set(partition) <= allowed_partition_fields)
            self.assertIn(
                partition["role"], partition_schema["properties"]["role"]["enum"]
            )
            self.assertTrue(
                all(isinstance(value, str) for value in partition["identifiers"].values())
            )

    def test_checked_in_schemas_state_their_non_authoritative_boundary(self) -> None:
        profile_schema = self.load_json(self.V2_SCHEMA)
        plan_schema = self.load_json(self.WRITE_PLAN_SCHEMA)
        for schema in (profile_schema, plan_schema):
            with self.subTest(schema_id=schema["$id"]):
                self.assertIn("Structural authoring aid only", schema["$comment"])
                self.assertIn("authoritative semantic validator", schema["$comment"])
                self.assertIn("does not authorize", schema["$comment"])

        u64_max = 18446744073709551615
        u32_max = 4294967295
        self.assertEqual(
            profile_schema["properties"]["whole_size"]["maximum"], u64_max
        )
        self.assertEqual(
            profile_schema["properties"]["sector_size"]["maximum"], u32_max
        )
        self.assertEqual(
            profile_schema["properties"]["prefix"]["properties"]["size"][
                "maximum"
            ],
            u64_max,
        )
        partition = profile_schema["$defs"]["partition"]["properties"]
        self.assertEqual(partition["number"]["maximum"], u32_max)
        self.assertEqual(partition["offset"]["maximum"], u64_max)
        self.assertEqual(partition["size"]["maximum"], u64_max)

        source = plan_schema["$defs"]["source"]["properties"]
        attestation = plan_schema["$defs"]["range"]["properties"]
        self.assertEqual(source["size"]["maximum"], u64_max)
        self.assertEqual(attestation["offset"]["maximum"], u64_max)
        self.assertEqual(attestation["length"]["maximum"], u64_max)
        self.assertEqual(
            plan_schema["properties"]["target_stable_id"]["pattern"], r"\S"
        )
        disposable = plan_schema["$defs"]["precondition"]["oneOf"][1]
        self.assertEqual(disposable["properties"]["rationale"]["pattern"], r"\S")

    def test_fast_card_v2_fixture_has_exact_geometry_and_no_legacy_fields(self) -> None:
        profile = self.load_json(self.V2_PROFILE)
        self.assertEqual(
            set(profile),
            {
                "format_version",
                "profile_id",
                "target",
                "whole_size",
                "sector_size",
                "partition_scheme",
                "prefix",
                "partitions",
            },
        )
        self.assertEqual(set(profile["prefix"]), {"size", "sha256"})

        cursor = profile["prefix"]["size"]
        for number, partition in enumerate(profile["partitions"], start=1):
            self.assertEqual(
                set(partition),
                {"role", "number", "offset", "size", "mbr", "filesystem", "identifiers"},
            )
            self.assertEqual(partition["number"], number)
            self.assertEqual(partition["offset"], cursor)
            self.assertEqual(partition["offset"] % profile["sector_size"], 0)
            self.assertEqual(partition["size"] % profile["sector_size"], 0)
            self.assertNotIn("volume_uuid", partition)
            self.assertNotIn("partuuid", partition)
            cursor += partition["size"]

        self.assertEqual(cursor, profile["whole_size"])
        self.assertNotIn("card", profile)
        self.assertNotIn("uboot", profile)
        self.assertNotIn("fallback", profile)
        self.assertNotIn("g92_prefix_size", profile)
        self.assertNotIn("g92_prefix_sha256", profile)


class MacosNativeReadOnlySourceTests(unittest.TestCase):
    SOURCE = (
        REPO_ROOT
        / "mainline"
        / "tools"
        / "r46h-card-toolchain"
        / "crates"
        / "r46h-card-core"
        / "src"
        / "macos_native.c"
    )

    @classmethod
    def setUpClass(cls) -> None:
        cls.source = cls.SOURCE.read_text(encoding="utf-8")

    @classmethod
    def function_body(cls, name: str) -> str:
        declarations = re.finditer(
            rf"(?m)^[A-Za-z_][^;{{\n]*\b{re.escape(name)}\(", cls.source
        )
        for declaration in declarations:
            start = declaration.start()
            opening = cls.source.index("{", start)
            semicolon = cls.source.find(";", start, opening)
            if semicolon == -1:
                break
        else:
            raise AssertionError(f"missing C function: {name}")
        depth = 0
        for index in range(opening, len(cls.source)):
            if cls.source[index] == "{":
                depth += 1
            elif cls.source[index] == "}":
                depth -= 1
                if depth == 0:
                    return cls.source[opening + 1 : index]
        raise AssertionError(f"unterminated C function: {name}")

    def test_native_surface_has_no_raw_write_primitive(self) -> None:
        forbidden = (
            "O_RDWR",
            "O_WRONLY",
            "pwrite(",
            "write(",
            "fsync(",
            "DKIOCSYNCHRONIZECACHE",
        )
        for token in forbidden:
            with self.subTest(token=token):
                self.assertNotIn(token, self.source)
        self.assertIn("O_RDONLY | O_NOFOLLOW | O_CLOEXEC", self.source)
        self.assertIn("pread(", self.source)

    def test_external_path_identity_uses_the_mounted_device(self) -> None:
        resolver = self.function_body("path_whole_disk")
        self.assertIn("statfs(path, &filesystem)", resolver)
        self.assertIn("filesystem.f_mntfromname", resolver)
        self.assertIn("DADiskCreateFromBSDName", resolver)
        self.assertNotIn("DADiskCreateFromVolumePath", self.source)

    def test_partition_probe_reads_raw_and_resolves_block_identity(self) -> None:
        partition = self.function_body("r46h_macos_partition_observation")
        self.assertIn('"/dev/r%ss%u"', partition)
        self.assertIn("open(partition_raw_path, O_RDONLY", partition)
        self.assertIn("DADiskCreateFromBSDName", partition)
        self.assertIn("partition_path", partition)

    def test_claim_unmount_and_eject_state_is_preallocated_and_ordered(self) -> None:
        claim = self.function_body("r46h_macos_claim_readonly")
        self.assertLess(claim.index("DADiskClaim("), claim.index("DADiskUnmount("))
        self.assertLess(
            claim.index("session->eject_result = calloc"),
            claim.index("DADiskUnmount("),
        )
        self.assertEqual(claim.count("DADiskUnmount("), 1)
        self.assertLess(claim.index("DADiskUnmount("), claim.index("open(actual.raw_path"))

    def test_eject_deny_is_consumed_before_retry_and_drop_retries(self) -> None:
        eject = self.function_body("eject_session")
        self.assertIn(
            "wait_status != 0 && !session->eject_result->completed",
            eject,
        )
        self.assertLess(
            eject.index("if (!session->eject_result->completed)"),
            eject.index("if (session->eject_result->denied)"),
        )
        self.assertIn("session->eject_pending = 0", eject)
        self.assertIn("memset(session->eject_result, 0", eject)

        release = self.function_body("r46h_macos_session_free")
        self.assertIn("session->unmounted && !session->ejected", release)
        self.assertLess(release.index("eject_session(session)"), release.index("release_session(session)"))


def stat_mode(path: Path) -> int:
    return os.stat(path).st_mode & 0o777


if __name__ == "__main__":
    unittest.main()
