#!/bin/sh
# Invoked inside Foot's PTY: keep desktop SDK settings out of Bash.
set -eu
[ "$(id -u)" != 0 ] || { echo 'Terminal must run as the desktop user.' >&2; exit 2; }
unset LD_LIBRARY_PATH LD_PRELOAD QT_PLUGIN_PATH QML_IMPORT_PATH QML2_IMPORT_PATH
unset QT_IM_MODULE QT_QPA_PLATFORM QT_QPA_EGLFS_INTEGRATION QSG_RHI_BACKEND QT_QUICK_BACKEND
unset XDG_CONFIG_HOME XDG_CACHE_HOME XDG_DATA_HOME TMPDIR
unset GBM_BACKENDS_PATH GBM_BACKEND __EGL_VENDOR_LIBRARY_FILENAMES LIBGL_DRIVERS_PATH
unset R46H_SHELL_LOG R46H_DEVICE_CONTROLS R46H_SHELL_STATE_DIR R46H_VIRTUAL_KEYBOARD
unset FONTCONFIG_FILE FONTCONFIG_PATH
# Keep WAYLAND_DISPLAY/XDG_RUNTIME_DIR, TERM and the caller's real HOME.
cd "$HOME"
exec /bin/bash --login
