#!/bin/bash
set -Eeuo pipefail

PATH=/usr/sbin:/usr/bin:/sbin:/bin
LC_ALL=C
LANG=C
export PATH LC_ALL LANG

readonly SCREENSHOT=/usr/local/bin/r46h-screenshot
readonly INPUT=/usr/local/libexec/r46h-remote-input
readonly ORIGINAL_COMMAND=${SSH_ORIGINAL_COMMAND-}

die() {
  printf 'ERROR: R46H remote key does not authorize this command\n' >&2
  exit 1
}

(( EUID == 1000 )) || die
[[ "$(id -g)" == 1000 ]] || die
[[ -n "${SSH_CONNECTION-}" ]] || die
[[ -z "${SSH_TTY-}" ]] || die
[[ -x "$SCREENSHOT" && ! -L "$SCREENSHOT" ]] || die

case $ORIGINAL_COMMAND in
  "$SCREENSHOT")
    exec "$SCREENSHOT"
    ;;
  *)
    if [[ "$ORIGINAL_COMMAND" =~ ^/usr/local/bin/r46h-screenshot[[:space:]]+(--read|--remove)[[:space:]]+(r46h-screen-[0-9]{8}T[0-9]{6}Z-[1-9][0-9]*\.png)[[:space:]]+([1-9][0-9]*)[[:space:]]+([0-9a-f]{64})$ ]]; then
      exec "$SCREENSHOT" "${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}" \
        "${BASH_REMATCH[3]}" "${BASH_REMATCH[4]}"
    fi
    if [[ "$ORIGINAL_COMMAND" =~ ^r46h-input[[:space:]]+(up|down|left|right|a|b|x|y|select|start|l1|r1|l2|r2|l3|r3)$ ]]; then
      [[ -x "$INPUT" && ! -L "$INPUT" ]] || die
      exec /usr/bin/sudo -n -- "$INPUT" "${BASH_REMATCH[1]}"
    fi
    die
    ;;
esac
